language: c

compiler:
    - gcc

git:
  submodules: false

before_install:
    - git submodule update --init --remote --recursive
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules

install:

script:  
    - make -j
